version: "3.8"

services:
  database:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_LOCAL_PORT}:${DATABASE_DOCKER_PORT}
    volumes:
      - db_volume:/data/db
    networks:
      - app-networks

  backend:
    depends_on:
      - database
    image: ndeyefatouniassy/backend:v1.1.1
    restart: unless-stopped
    container_name: backend
    env_file: ./.env
    ports:
      - ${APP_LOCAL_PORT}:${APP_DOCKER_PORT}
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
    networks:
      - app-networks

networks:
  app-networks:

volumes:
  db_volume:
