apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: devops-project
type: Opaque
data:
  mongo-username: ZmF0b3U=  # "fatou" encodé en base64
  mongo-password: cGFzc2Vy  # "passer" encodé en base64